# Generated by Django 5.0.5 on 2024-05-10 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_description_alter_task_performer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='performer',
            new_name='executor',
        ),
    ]
